import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/normalize.css";
import "./styles/reset.css";

export const metadata: Metadata = {
  title: "Droguerías Alkosto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
